[17:33] Talluri,M,Maheedhar,TAF2 C
    
FROMubuntu:16.04
RUNapt-getupdate \
&&apt-getinstall-ynginx \
&&apt-getclean \
&&rm-rf/var/lib/apt/lists/*/tmp/*/var/tmp/* \
&&echo"daemonoff;">>/etc/nginx/nginx.conf
EXPOSE80
CMD["nginx"]
